language: python

jobs:
 include:
  - name: "Python Windows Build"
    arch: amd64
    os: windows
    language: shell
    python:
     - "3.6"
     - "3.7"
     - "3.8"

  - name: "Python RPi Build"
    arch: arm64
    os: linux
    python:
     - "3.6"
     - "3.7"
     - "3.8"

  allow_failures:
    - arch: "arm64"

cache:
  - pip

install: pip install -r requirements.txt

script:
  - python -m pytest