language: python

jobs:
 include:
  - name: "Python Windows Build 3.6"
    arch: amd64
    os: windows
    language: shell
    python: 3.6
    before_install:
     - choco install python --version 3.6.0
     - python -m pip install --upgrade pip
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

  - name: "Python Windows Build 3.7"
    arch: amd64
    os: windows
    language: shell
    python: 3.7
    before_install:
     - choco install python --version 3.7.0
     - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

  - name: "Python Windows Build 3.8"
    arch: amd64
    os: windows
    language: shell
    python: 3.8
    before_install:
     - choco install python --version 3.8.0
     - python -m pip install --upgrade pip
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

  - name: "Python RPi Build 3.6"
    arch: arm64
    os: linux
    python: 3.6

  - name: "Python RPi Build 3.7"
    arch: arm64
    os: linux
    python: 3.7

  - name: "Python RPi Build 3.8"
    arch: arm64
    os: linux
    python: 3.8

 allow_failures:
  - arch: arm64
 fast_finish: true

cache:
  - pip

install:
 - pip3 install -r requirements.txt
 - pip3 install pytest

script:
  - python3 -m pytest || python -m pytest

after_success:
  - git checkout master && git merge development -m "Merge successful development build"